Ngoat = input ("How many goats?")
Ngoat = int (Ngoat)
Kapples = input ("How many apples?")
Kapples = int (Kapples)
result = ( Kapples // Ngoat )
result = int (result)
print ("Each goat will receive ",result, "apples.")
Secondresult = (Kapples % Ngoat)
print (Secondresult, "apples will be left in the basket.")