one = input('How many goats?')
two = input('How many apples?')
int(one)
int(two)
three = (int(two)//int(one))
three = int(three)
print('Each goat will receive',three,'apples.')
five = (int(three)*int(one))
five = int(five)
six = (int(two)-int(five))
print(six,'apples will be left in the basket')